- hosts: all
  gather_facts: no
  become: yes
  tasks:
  #  - name: install Docker
  #    apt:
  #      name: docker.io
  #      state: present
  #      update_cache: true

  #  - name: install APT Transport HTTPS
  #    apt:
  #      name: apt-transport-https
  #      state: present
   
  #  - name: install pip3
  #    apt:
  #      name: python3-pip
  #      state: present
  #  - pip:
  #     name: docker
  #  - pip:
  #     name: docker-compose

     - name: copy Docker Compose files
       copy:
        src: docker-compose.yml
        dest: ~/docker-compose.yml

     - name: docker-compose up
       docker_service:
         project_src: ~/
         files:
          - "docker-compose.yml"
         state: present 
  #    register: output

  #  - debug:
  #      var: output    
   
  