- hosts: all
  become: yes
  tasks:
   - name: install Docker
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: install python3-pip
     apt:
       name: python3-pip
       state: present
       update_cache: true
  
   - name: install docker-py
     pip:
       name: docker-py
       state: present

   - name: install docker-compose
     pip:
       name:  docker-compose
       state: present
       
   - name: create and start services
     docker_service:
       project_src: "{{ playbook_dir }}"
       state: present